---
title: "player_search"
output: html_document
date: "2022-08-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load packages
suppressMessages({
  library(nflverse) #	Easily Install and Load the 'nflverse'
  library(tidyverse) # Easily Install and Load the 'Tidyverse'
  library(ggrepel) # Automatically Position Non-Overlapping Text Labels with 'ggplot2'
  library(ggimage) # Use Image in 'ggplot2'
  library(gt) # Easily Create Presentation-Ready Display Tables
  library(paletteer) # Comprehensive Collection of Color Palettes
})
```

Load the position group
```{r}
rbs <- read_csv("./01_data/Training_Data/position_groups/rbs.csv")
str(rbs, give.attr=F)
```
```{r}
player_search <- function(name){
  rbs_player <- rbs %>% 
    filter(player == name) %>% 
    group_by(year) %>% 
    summarise(
      team = team_name,
      run_plays = last(run_plays),
      grades_offense = round(mean(grades_offense), digits = 1),
      grades_run = round(mean(grades_run), digits = 1),
      grades_pass_route = round(mean(grades_pass_route), digits = 1),
      
      attempts = last(attempts),
      gap_attempts = last(gap_attempts), 
      zone_attempts = last(zone_attempts), 
      yards = last(yards),
      elusive_rating = round(mean(elusive_rating), digits = 1),
      ypa = round(mean(ypa), digits = 1), 
      yco_attempt = round(mean(yco_attempt), digits = 1), 
      
      routes = last(routes), 
      receptions = last(receptions),
      yprr = round(mean(yprr), digits =1),
      targets_per_game = round(mean(round(targets / player_game_count, digits = 1)),  digits = 1), 
      
      total_touches_per_game = round(mean(round(total_touches / player_game_count, digits =1)),  digits = 1), 
      touchdowns = last(touchdowns), 
      fumbles = last(fumbles)) %>% 
    arrange(-year) %>% 
    distinct()
  
  gt <- gt(rbs_player) %>% 
    tab_header(paste(name, "Summary")) %>% 
    tab_spanner(
      label = "Grades", 
      columns = c(run_plays,grades_offense, grades_run, grades_pass_route)
    ) %>% 
    tab_spanner(
      label = "Rushing", 
      columns = c(attempts, gap_attempts, zone_attempts, yards, elusive_rating, ypa, yco_attempt)
    ) %>% 
    tab_spanner(
      label = "Passing", 
      columns = c(routes, receptions, yprr, targets_per_game)
    ) %>% 
    tab_spanner(
      label = "Production", 
      columns = c(total_touches_per_game, touchdowns,fumbles)
    ) %>% 
    data_color(
      columns = grades_offense, 
      colors = scales::col_numeric(
      palette = paletteer::paletteer_d(
        palette = "ggsci::red_material"
      ) %>%
        as.character(),
      domain = NULL
      ))
  
  gtsave(gt, filename = paste("./03_plots/", Sys.Date(), name, "summary.html"))
  
  gt(rbs_player) %>% 
    tab_header(paste(name, "Summary"))
}

player_search("Derrick Henry")
```
